### ISSUE TITLE
Add an option for users to seed via WebTorrent (as an added library to libtorrent)

### ISSUE THREAD

**Issue by rigelk** [StCyr/plugin.video.peertube#1]
As @Chocobozzz suggested, seeding over TCP/UDP with the current `libtorrent` is fine, as machines running Kodi are not always powerful ones and might want to avoid running the extra Electron process required to use WebTorrent/WebRTC.

`libtorrent` isn't gonna add support for WebTorrent anytime soon, so I'd suggest add another library to deal with WebTorrent: [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid). It is basically the same API as the original `webtorrent` package, but runs headlessly outside of a browser and is maintained by the same authors. Of course, it's an added dependency and *it is not Python code*, so you will have to create bindings to the Javascript library. But as no other alternative exists in Python, that's the only way.

However, using `webtorrent-hybrid` allows to download from/share to web clients of PeerTube. That's particularly interesting since Kodi is a long-running server and can seed headlessly for quite some time.

**Comment by StCyr** [comment]
Hello,

I 100% agree that supporting webtorrent would be great for the peertube ecosystem.

However, I've 3 issues with your proposal of using `webtorrent-hybrid`:

1. I have 0 experience using such bindings. If I understand correctly I would need something like https://github.com/sqreen/PyMiniRacer or https://code.google.com/archive/p/pyv8. Is it so?
2. Adding such bindings might break Kodi's rules for becoming an official add-on (https://kodi.wiki/view/Add-on_rules), while becoming an official add-on might be a benefit for the peertube fediverse
3. The projects mentionned at point 1 hereabove don't seem very-well maintained.

**Comment by rigelk** [comment]
@StCyr I can't see where in the documentation including JavaScript is formally forbidden. Most of the documentation revolves around using the exposed APIs for the tasks, but they can't possibly cover all cases.

As for the binding to JS, I'm pretty new to this myself, but you have a point that they don't seem regularly maintained at first sight. I'll have a closer look.

**Comment by StCyr** [comment]
Thanks for the help @rigelk 

Regarding Kodi's rules, I'm refering to the fact that they don't allow pre-compiled binaries. But, I must admit I haven't looked at it very closely yet :-)

**Comment by StCyr** [comment]
It seems that Kodi's team is not really eager to see such an addon being part of their official repository. 

Also, they mentionned that `libtorrent` is already a binding around `libtorrent-rasterball`.

So, `webtorrent-hybrid` might just be as good of a solution in the end. 

There's still this apparent lack of maintenance though.

**Comment by rigelk** [comment]
@StCyr did you just ask the Kodi team?

**Comment by StCyr** [comment]
Yes, informally, via their IRC channel.

In fact, I asked about something else. And, the person who answered also pointed that he doubt this add on would be accepted in their official repo

**Comment by rigelk** [comment]
Well, at least that settles things.

I'll investigate the JS to Python import then.

**Comment by rigelk** [comment]
@StCyr after checking there's really no ideal solution. You might want to directly use subprocesses… :/

**Comment by StCyr** [comment]
This issue has been created on https://framagit.org/StCyr/plugin.video.peertube

Closing it here
