### ISSUE TITLE
How to install this git project within kodi ?

### ISSUE THREAD

**Issue by artlog** [StCyr/plugin.video.peertube#2]
I think we are all reading french here, but for sake of global understanding i stick to english even if shakespear might die again.

I decided to play it easy so i get kodi on my debian and activated external source to be abel to import a zip. my future goal is to get it working on my osmc system.

So my basic question : what is the way to build a .zip addon from this repository content ?

I would like to test it and perhaps help if my brain decide to follow.

Oops i forgot : THANKS a LOT for this stuff !

**Comment by StCyr** [comment]
Hi,

Yes I'm a French speaker also. :-)

You're right: I should probably publish a release of this addon to help people use it.

For now on, I think you should be able to install this addon as follow:

1. **Create the zip file**

```
git clone https://github.com/StCyr/plugin.video.peertube
zip -r plugin.video.peertube.zip plugin.video.peertube
```

2. **Install the addon**

See https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

Hope this help!

Cyrille

**Comment by artlog** [comment]
thanks ! I does help.

This seems obvious but i lost one hour trying to create this zip.
i just learn that it should be plugin.video.peertube directory and not directly directory content.
I did fork it on framagit working on it.

**Comment by StCyr** [comment]
Cool.

I Hope you'll like peertube :-)

Cheers!

Le ven. 23 nov. 2018 à 11:08, philippe lhardy <notifications@github.com> a
écrit :

**Comment by artlog** [comment]
en français sur framagit...

**Comment by thombet** [comment]
I close this ticket since it was implemented in framagit: https://framagit.org/StCyr/plugin.video.peertube/-/merge_requests/1
