### ISSUE TITLE
Login?

### ISSUE THREAD

**Issue by ghost** [StCyr/plugin.video.peertube#3]
Will there ever be a way to log in and see our subscriptions, etc?

**Comment by thombet** [comment]
Hello @Skaalgard,
This repo is just for visibility but the actual development occurs in the Framagit version: https://framagit.org/StCyr/plugin.video.peertube
Could you please open a ticket there?
I don't know when I will implement the features related to the accounts but I will definitively have a look to it at some point.
It may also be useful to know which features you expect in the ticket 😉

**Comment by ghost** [comment]
I have opened a ticket on Framagit here: https://framagit.org/StCyr/plugin.video.peertube/-/issues/13

**Comment by thombet** [comment]
Thanks, I will close this ticket then.
